# Bungee CTW Lobby Configuration File | v1.0
ctwlobby-server: lobby # Required.

game-servers: # Names of your game servers for BungeeCord, required.
  - room-1
  - room-2
  - room-3

# Sign Settings
signs:
  first-line-text: "ctw" # Text to type into sign to create a CTW sign.

# Lobby Settings
lobby:
  guard: true
  items: true
  scoreboard: true

# Sound Settings
sounds:
  enabled: true
  alert: NOTE_PLING
  gui: CHEST_OPEN
  your-stats: ORB_PICKUP
  error: ENDERDRAGON_HIT
  tip: ITEM_PICKUP